baseURL = 'https://mhed89.github.io/'
languageCode = 'sv'
title = 'Markus Hedenborn'
theme = 'archie'
copyright = "© 2026"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  mode = "light"
  useCDN = false
  subtitle = "Hjärndump där jag sätter ord på mina tankar & idéer."
  mainSections = ["posts"]

[[menu.main]]
name = "Hem"
url = "/"
weight = 1

[[menu.main]]
name = "Inlägg"
url = "/posts"
weight = 2

[[menu.main]]
name = "Om"
url = "/about"
weight = 3